import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { useEffect } from "react";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // console.log("layout => ", children);

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
      {children}
      </Provider>
      </body>
    </html>
  );
}
