import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // console.log("layout", children)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="grid grid-cols-[250px,_1fr] w-full h-screen">
            <Sidebar />
            <div className="bg-indigo-100 text-black overflow-y-scroll">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
